gravatar:
  default_size: 80
  normal_size: 50
url:
  gravatar: https://secure.gravatar.com/avatar/
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
validate:
  max_board_name: 35
  max_board_description: 255
  max_label_content: 35
data:
  confirm: 1
  notconfirm: 0
image:
  accept_types: "image/jpeg, image/gif, image/png"
tag:
  name:
    length: 200
  description:
    length: 1000
number:
  zero: 0
  one: 1
validate:
  max_board_name: 40
  max_board_description: 255
  max_list_name: 30
  max_label_content: 30
